#[derive(Debug)]
pub enum System {
	Windows,
	Linux,
	FreeBSD,
	Apple,
	Solaris,
	NetBSD,
	ChromeOS,
	CoreOS,
	Haiku,
	MidnightBSD,
	Ceph,
	OpenBSD,
	QNX,
	VMware,
	AndroidIA,
	AndroidARM,
	ONIE,
	AtariTOS,
}

#[derive(Debug)]
pub enum PartitionType {
	UnusedEntry,
	MBRPartition,
	EFIPartition,
	BIOSBootPartition,
	IntelFastFlashPartition,
	SonyBootPartition,
	LenovoBootPartition,

	MicrosoftReservedPartition,
	WindowsBasicDataPartition,
	WindowsLogicalDiskManagerMetadataPartition,
	WindowsLogicalDiskManagerDataPartition,
	WindowsRecoveryEnvironmentPartition,
	WindowsIBMGPFSPartition,
	WindowsStorageSpacesPartition,
	WindowsHPUXDataPartition,
	WindowsServicePartition,

	LinuxFilesystemDataPartition,
	LinuxRaidPartition,
	LinuxRaidx86Partition,
	LinuxRaidx8664Partition,
	LinuxRaid32ARMPartition,
	LinuxRaid64ARMPartition,
	LinuxSwapPartition,
	LinuxLogicalVolumeManagerPartition,
	LinuxHomePartition,
	LinuxServerPartition,
	LinuxDMCryptPartition,
	LinuxLUKSPartition,
	LinuxReservedPartition,

	FreeBSDBootPartition,
	FreeBSDDataPartition,
	FreeBSDSwapPartition,
	FreeBSDUFSPartition,
	FreeBSDVinumVolumeManagerPartition,
	FreeBSDZFSPartition,

	AppleHFSPartition,
	AppleFSPartition,
	AppleUFSPartition,
	AppleZFSPartition,
	AppleRaidPartition,
	AppleRaidOfflinePartition,
	AppleBootPartition,
	AppleLabelPartition,
	AppleTVRecoveryPartition,
	AppleCoreStoragePartition,

	SoftRAIDStatusPartition,
	SoftRAIDScratchPartition,
	SoftRAIDVolumePartition,
	SoftRAIDCachePartition,

	SolarisBootPartition,
	SolarisRootPartition,
	SolarisSwapPartition,
	SolarisBackupPartition,
	SolarisUsrPartition,
	SolarisVarPartition,
	SolarisHomePartition,
	SolarisAlternateSectorPartition,
	SolarisReservedPartition,

	NetBSDSwapPartition,
	NetBSDFFSPartition,
	NetBSDLFSPartition,
	NetBSDRaidPartition,
	NetBSDConcatenatedPartition,
	NetBSDEncryptedPartition,

	ChromeOSKernelPartition,
	ChromeOSRootFSPartition,
	ChromeOSFuturePartition,

	CoreOSUsrPartition,
	CoreOSResizePartition,
	CoreOSReservedPartition,
	CoreOSRootRaidPartition,

	HaikuBFSPartition,

	MidnightBSDBootPartition,
	MidnightBSDDataPartition,
	MidnightBSDSwapPartition,
	MidnightBSDUFSPartition,
	MidnightBSDVinumVolumeManagerPartition,
	MidnightBSDZFSPartition,

	CephJournalPartition,
	CephDMCryptJournalPartition,
	CephOSDPartition,
	CephDMCryptOSDPartition,
	CephDiskInCreationPartition,
	CephDMCryptDiskInCreationPartition,
	CephBlockPartition,
	CephBlockDBPartition,
	CephBlockWriteAhedLogPartition,
	CephDMCryptLockboxPartition,
	CephMultipathOSDPartition,
	CephMultipathJournalPartition,
	CephMultipathBlockPartition,
	CephMultipathBlockDBPartition,
	CephMultipathBlockWriteAhedLogPartition,
	CephDMCryptBlockPartition,
	CephDMCryptBlockDBPartition,
	CephDMCryptBlockWriteAhedLogPartition,
	CephDMCryptLUKSJournalPartition,
	CephDMCryptLUKSBlockPartition,
	CephDMCryptLUKSBlockDBPartition,
	CephDMCryptLUKSBlockWriteAhedLogPartition,
	CephDMCryptLUKSOSDPartition,

	OpenBSDDataPartition,

	QNXPowerSafePartition,

	VMWareVMCorePartition,
	VMWareFilesystemPartition,
	VMWareReservedPartition,

	AndroidIABootloaderPartition,
	AndroidIABootloader2Partition,
	AndroidIABootPartition,
	AndroidIARecoveryPartition,
	AndroidIAMiscPartition,
	AndroidIAMetadataPartition,
	AndroidIASystemPartition,
	AndroidIACachePartition,
	AndroidIADataPartition,
	AndroidIAPersistentPartition,
	AndroidIAVendorPartition,
	AndroidIAConfigPartition,
	AndroidIAFactoryPartition,
	AndroidIAFastbootPartition,
	AndroidIAOEMPartition,

	AndroidARMMetaPartition,
	AndroidARMEXTPartition,

	ONIEBootPartition,
	ONIEConfigPartition,

	AtariTOSBasicDataPartition,
}
